volumes:
  mainnet-lite-volume:
  testnet-lite-volume:

networks:
  subtensor:
    name: subtensor

services:
  common-amd64: &common-amd64 # image: ghcr.io/opentensor/subtensor:v2.0.9-amd64
    image: ghcr.io/opentensor/subtensor:v3.1.0-amd64@sha256:054e9c989cd5a43a6f70fe8cf76cc7e8947eaed3d9cbd8b3dd5df047f1e7e346
    build:
      context: .
      dockerfile: Dockerfile
      target: subtensor
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    networks:
      - subtensor
    ports:
      # NOTE: uncomment these when you want to expose them
      # - "9944:9944"
      - "30333:30333"
      # - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    logging:
      options:
        max-size: "100m"

  mainnet-lite-amd64:
    <<: *common-amd64
    container_name: subtensor-mainnet-lite
    volumes:
      - mainnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec_finney.json \
          --rpc-external --rpc-cors all \
          --no-mdns \
          --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp

  testnet-lite-amd64:
    <<: *common-amd64
    container_name: subtensor-testnet-lite
    volumes:
      - testnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec_testfinney.json \
          --rpc-external --rpc-cors all \
          --no-mdns \
          --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.test.finney.opentensor.ai/tcp/30333/p2p/12D3KooWPM4mLcKJGtyVtkggqdG84zWrd7Rij6PGQDoijh1X86Vr \
          --sync warp
          --reserved-nodes /dns/bootnode.test.finney.opentensor.ai/tcp/30333/p2p/12D3KooWPM4mLcKJGtyVtkggqdG84zWrd7Rij6PGQDoijh1X86Vr \
          --reserved-only

  common-arm64: &common-arm64 # image: ghcr.io/opentensor/subtensor:v2.0.9-arm64
    image: ghcr.io/opentensor/subtensor:v3.1.0-arm64@sha256:3adc616fb62811007a59ef92942b0bd56fccc877a717c86012d4583566219a29
    build:
      context: .
      dockerfile: Dockerfile
      target: subtensor
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    networks:
      - subtensor
    ports:
      # NOTE: uncomment these when you want to expose them
      # - "9944:9944"
      - "30333:30333"
      # - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    logging:
      options:
        max-size: "100m"

  mainnet-lite-arm64:
    <<: *common-arm64
    container_name: subtensor-mainnet-lite
    volumes:
      - mainnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain ./chainspecs/raw_spec_finney.json \
          --rpc-external --rpc-cors all \
          --no-mdns \
          --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --sync warp

  testnet-lite-arm64:
    <<: *common-arm64
    container_name: subtensor-testnet-lite
    volumes:
      - testnet-lite-volume:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec_testfinney.json \
          --rpc-external --rpc-cors all \
          --no-mdns \
          --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.test.finney.opentensor.ai/tcp/30333/p2p/12D3KooWPM4mLcKJGtyVtkggqdG84zWrd7Rij6PGQDoijh1X86Vr \
          --sync warp
          --reserved-nodes /dns/bootnode.test.finney.opentensor.ai/tcp/30333/p2p/12D3KooWPM4mLcKJGtyVtkggqdG84zWrd7Rij6PGQDoijh1X86Vr \
          --reserved-only
