version: "3.8"

networks:
  validator:
    name: validator

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile-cli
    networks:
      - validator
    image: dojo-cli:local
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./scores.json:/app/scores.json
    working_dir: /app
