# Builder stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git ca-certificates
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o ./cli ./cmd/cli

# Final image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/cli .
RUN chmod +x ./cli
ENTRYPOINT ["/app/cli"]
