x-logging: &default-logging
  options:
    max-size: "50m"

#x-miner-defaults: &miner-defaults
#  image: ghcr.io/tensorplex-labs/dojo:main
#  env_file:
#    - .env
#  working_dir: /app
#  volumes:
#    - ./:/app
#    - ./.env:/app/.env
#    - $BITTENSOR_DIR:/root/.bittensor
#  command: ["miner"]
#  ports:
#    - ${AXON_PORT}:${AXON_PORT}
#  networks:
#    - dojo-miner
#    - subtensor
#  logging: *default-logging

networks:
  dojo-miner:
    driver: bridge
  dojo-platform:
    name: dojo-platform
  # Applicable only for sidecar and miner service
  subtensor:
    name: subtensor

services:
  dojo-cli:
    image: ghcr.io/tensorplex-labs/dojo:main
    container_name: dojo-cli
    volumes:
      - ./:/app
      - ./.env:/app/.env
      - $BITTENSOR_DIR:/root/.bittensor
    command: ["dojo-cli"]
    tty: true
    stdin_open: true
    networks:
      - dojo-miner

  miner:
    image: ghcr.io/tensorplex-labs/dojo:main
    container_name: miner
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
      - ./.env:/app/.env
      - $BITTENSOR_DIR:/root/.bittensor
    command: ["miner"]
    ports:
      - ${AXON_PORT}:${AXON_PORT}
    networks:
      - dojo-miner
      - dojo-platform
      - subtensor
    logging: *default-logging

#  miner-centralised:
#    <<: *miner-defaults
#    container_name: miner-centralised
#
#  miner-decentralised:
#    <<: *miner-defaults
#    container_name: miner-decentralised
#    depends_on:
#      worker-api:
#        condition: service_healthy
#      worker-ui:
#        condition: service_healthy
