x-logging: &default-logging
  options:
    max-size: "50m"

networks:
  dojo-miner:
    driver: bridge
  dojo-platform:
    name: dojo-platform
  # Applicable only for sidecar and miner service
  subtensor:
    name: subtensor

volumes:
  redis-miner-volume:

services:
  #  watchtower:
  #    extends:
  #      file: docker-compose.shared.yaml
  #      service: watchtower
  redis:
    extends:
      file: docker-compose.shared.yaml
      service: redis
    volumes:
      - redis-miner-volume:/data
    networks:
      - dojo-miner

  dojo-cli:
    container_name: dojo-cli
    image: ghcr.io/tensorplex-labs/dojo:main
    volumes:
      - ./.env:/app/.env
      - $BITTENSOR_DIR:/root/.bittensor
    command: ["dojo-cli"]
    tty: true
    stdin_open: true
    networks:
      - dojo-miner
      - dojo-platform

  miner:
    container_name: miner
    image: ghcr.io/tensorplex-labs/dojo:main
    restart: on-failure
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - $BITTENSOR_DIR:/root/.bittensor
    command: ["miner"]
    ports:
      - ${AXON_PORT}:${AXON_PORT}
    networks:
      - dojo-miner
      - dojo-platform
      - subtensor
    logging: *default-logging
    depends_on:
      kami:
        condition: service_healthy
      redis:
        condition: service_healthy

  kami:
    extends:
      file: docker-compose.shared.yaml
      service: kami
    networks:
      - subtensor
