services:
  kami:
    container_name: kami
    restart: on-failure
    image: ghcr.io/tensorplex-labs/kami:main
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env_file:
      - .env
    # ports:
    #   - 3000:3000
    expose:
      - $KAMI_PORT
    # logging: *default-logging
    # volumes:
      # - ${BITTENSOR_DIR}:${BITTENSOR_DIR}
    # networks:
    #   - subtensor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${KAMI_HOST}:${KAMI_PORT}/substrate/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 50s
