FROM python:3.11-slim-bookworm

WORKDIR /app

ENV PATH="/root/.cargo/bin/:$PATH"
ENV UV_SYSTEM_PYTHON=true
ENV NVM_DIR=/root/.nvm
ENV NODE_VERSION=v20.11.1
ENV NODE_PATH=$NVM_DIR/versions/node/$NODE_VERSION/lib/node_modules
ENV PATH=$NVM_DIR/versions/node/$NODE_VERSION/bin:$PATH

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    build-essential curl git ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g uglify-js

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
COPY . .
RUN chmod +x entrypoints.sh

ARG TARGETPLATFORM

RUN echo "Building for TARGETPLATFORM: $TARGETPLATFORM"

RUN git config --global --add safe.directory /app
RUN git config --unset 'http.https://github.com/.extraheader'

# jank because pytorch has different versions for cpu for darwin VS linux, see pyproject.toml for specifics
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    uv pip install --no-cache -e . --find-links https://download.pytorch.org/whl/torch_stable.html; \
    else \
    uv pip install --no-cache -e .; \
    fi

ENTRYPOINT ["./entrypoints.sh"]
