name: Docker Build and Push

on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      tag_name:
        required: false
        type: string

jobs:
  docker_publish:
    name: Build (${{ matrix.app.name }})
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
      actions: read

    strategy:
      matrix:
        app: ${{ fromJson(inputs.matrix).app }}
      max-parallel: 6
    steps:
      - name: Download binary artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: ${{ matrix.app.name }}-linux-*
          path: dist
          merge-multiple: true

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.app.name }}
          tags: |
            type=raw,value=${{ github.ref_name }},enable=${{ inputs.tag_name == '' && github.ref_type == 'branch' }}
            type=raw,value=${{ inputs.tag_name }},enable=${{ inputs.tag_name != '' }}
            type=raw,value=latest,enable=${{ inputs.tag_name != '' }}

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          platforms: ${{ join(fromJson(inputs.matrix).platform, ',') }}

      - name: Build and Publish
        uses: docker/build-push-action@v6.18.0
        with:
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: ${{ join(fromJson(inputs.matrix).platform, ',') }}
          build-contexts: |
            binaries=./dist
          build-args: |
            APP_NAME=${{ matrix.app.name }}
