name: Post Release

on:
  release:
    types:
      - published

jobs:
  post-release:
    runs-on: arc-runner-set
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    permissions:
      actions: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Build linux binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o dist/validator-linux-amd64 ./cmd/validator
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-w -s" -o dist/validator-linux-arm64 ./cmd/validator

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          files: |
            dist/*
