name: Create Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: arc-runner-set
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4.3.0
        with:
          release-type: go
